// <auto-generated />
namespace Democracia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20161215 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20161215));
        
        string IMigrationMetadata.Id
        {
            get { return "201612151650168_20161215"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
